BlogBundle_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
    requirements:
        _method:  GET

BlogBundle_about:
    path:     /about
    defaults: { _controller: BlogBundle:Default:about }
    requirements:
        _method:  GET

BlogBundle_contact:
    path:     /contact
    defaults: { _controller: BlogBundle:Default:contact }
    requirements:
        _method:  GET|POST

BlogBundle_blog_show:
    path:     /{id}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
